name: CI/CD Pipeline - BookShop Project 
on:
  push:
    branches:
      - master  # Trigger when pushing to master
    paths:
      - '.github/workflows/bookshop-build.yml'   
      - 'bookshop/**'  
  pull_request:
    branches:
      - master  # Trigger when creating a PR to master
    paths:
      - '.github/workflows/bookshop-build.yml'   
      - 'bookshop/**' 
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: bookstore
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uadmin -padmin -e "SHOW DATABASES;"

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Add DeepSource to PATH
        run: echo "$PWD/bin" >> $GITHUB_PATH

      - name: Verify DeepSource installation
        run: which deepsource && deepsource --help

      - name: Build Project
        run: cd bookshop && mvn clean package -DskipTests
      
      - name: Run Tests with JaCoCo
        run: |
          cd bookshop && mvn test jacoco:report
          ls target/site/jacoco/jacoco.xml 

      - name: Upload Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: cd bookshop && deepsource report --analyzer test-coverage --key java --value-file target/site/jacoco/jacoco.xml

