name: CI/CD Pipeline - BookShop Admin Project
on:
  push:
    branches:
      - master # Trigger when pushing to master
    paths:
      - ".github/workflows/bookshop-admin-build.yml"
      - "bookshop-admin/**"
  pull_request:
    branches:
      - master # Trigger when creating a PR to master
    paths:
      - ".github/workflows/bookshop-admin-build.yml"
      - "bookshop-admin/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build Project
        run: cd bookshop-admin && mvn clean package -DskipTests

      - name: Run Tests with JaCoCo
        run: cd bookshop-admin && mvn test jacoco:report

      - name: Upload Test Coverage to DeepSource
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key java --value-file bookshop-admin/target/site/jacoco/jacoco.xml

