name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci-cd-bookshop.yml"
      - "bookshop/**"
      - "bookshop-admin/**"
  pull_request:
    branches:
      - master

jobs:
  bookshop:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: bookstore
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uadmin -padmin -e "SHOW DATABASES;"

      - name: Build & Install BookShop
        run: |
          cd bookshop
          mvn clean install -DskipTests
          echo "BookShop build completed. JAR should now be in ~/.m2/repository."

      - name: Run Tests with JaCoCo
        run: |
          cd bookshop && mvn test jacoco:report
          ls target/site/jacoco/jacoco.xml

      - name: Upload BookShop Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer java

  bookshop-admin:
    runs-on: ubuntu-latest
    needs: bookshop # ✅ depends `bookshop` make sure `bookshop` compile finish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Restore Maven Dependencies (Ensure BookShop JAR is Available)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Bookshop-Admin
        run: |
          cd bookshop-admin
          mvn clean package -DskipTests
          echo "Bookshop-Admin built successfully using BookShop JAR from ~/.m2/repository."

      - name: Run Tests with JaCoCo
        run: |
          cd bookshop-admin && mvn test jacoco:report
          ls target/site/jacoco/jacoco.xml

      - name: Upload Bookshop-Admin Test Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer java